### ISSUE TITLE
Use @string resource for texts in activity_main.xml

### ISSUE THREAD

**Issue by Rohit1173** [Rohit1173/TODO-APP-FOSS#1]
There were a few texts in activity_main.xml and actvity_main.xml (land) which were hardcoded , Instead use `@string` resource and replace them

**Comment by superiorsd10** [comment]
@Rohit1173 Sir! I think I acquire enough knowledge to resolve this issue, so please consider assigning it to me.

**Comment by Rohit1173** [comment]
Assigned!
