### ISSUE TITLE
Shift the colors used in card.xml to colors.xml

### ISSUE THREAD

**Issue by Rohit1173** [Rohit1173/TODO-APP-FOSS#11]
There were a few colors in card.xml which should be transferred to colors.xml and they should be used in card.xml using `@color` resource

**Comment by superiorsd10** [comment]
@Rohit1173 Sir I think I acquire enough knowledge to resolve this issue, so please consider assigning it to me.

**Comment by Rohit1173** [comment]
Assigned!
