### ISSUE TITLE
Shift the dimensions of fragment_edit.xml to dimens.xml

### ISSUE THREAD

**Issue by Rohit1173** [Rohit1173/TODO-APP-FOSS#8]
Check the fragment_edit.xml and transfer every dimension value (i.e., represented in dp) to dimens.xml. After transferring you can use the @dimens to set the dimensions of a particular value

**Comment by superiorsd10** [comment]
@Rohit1173 Sir I think I acquire enough knowledge to resolve this issue, so please consider assigning it to me.

**Comment by Rohit1173** [comment]
Assigned!
